port: /dev/ttyUSB1
baud: 1000000
rate: 100
sync_write: True
sync_read: False
read_rate: 20
write_rate: 20

joints: {
  left_arm_joint1: {id: 1, neutral: 512, min_angle: -90, max_angle: 90},
  left_arm_joint2: {id: 2, neutral: 512, min_angle: 0, max_angle: 90},
  left_arm_joint3: {id: 3, neutral: 512, min_angle: -126, max_angle: 126},
  left_arm_joint4: {id: 4, neutral: 512, min_angle: -90, max_angle: 90},
  left_arm_joint5: {id: 5, neutral: 512, min_angle: -126, max_angle: 126},
  left_arm_joint6: {id: 6, neutral: 512, min_angle: -90, max_angle: 90},
  left_joint_gripper_r: {id: 8, neutral: 512, min_angle: 0, max_angle: 90},
  right_arm_joint1: {id: 9, neutral: 512, min_angle: -90, max_angle: 90},
  right_arm_joint2: {id: 10, neutral: 512, min_angle: -45, max_angle: 45},
  right_arm_joint3: {id: 11, neutral: 512, min_angle: -90, max_angle: 90},
  right_arm_joint4: {id: 12, neutral: 512, min_angle: -90, max_angle: 90},
  right_arm_joint5: {id: 13, neutral: 512, min_angle: -90, max_angle: 90},
  right_arm_joint6: {id: 14, neutral: 512, min_angle: -90, max_angle: 90},
  right_joint_gripper_l: {id: 15, neutral: 512},
  right_joint_gripper_r: {id: 16, neutral: 512}
}

controllers: {
 left_arm_controller: {
   onboard: False,
   action_name: left_arm_controller/follow_joint_trajectory,
   type: follow_controller,
   joints: [left_arm_joint1, left_arm_joint2, left_arm_joint3, left_arm_joint4, left_arm_joint5, left_arm_joint6]
 },

 left_gripper_controller: {
   onboard: False,
   action_name: left_gripper_controller/follow_joint_trajectory,
   type: follow_controller,
   joints: [left_joint_gripper_r]
 },

 right_arm_controller: {
   onboard: False,
   action_name: right_arm_controller/follow_joint_trajectory,
   type: follow_controller,
   joints: [right_arm_joint1, right_arm_joint2, right_arm_joint3, right_arm_joint4, right_arm_joint5, right_arm_joint6]
 },

 right_gripper_controller: {
   onboard: False,
   action_name: right_gripper_controller/follow_joint_trajectory,
   type: follow_controller,
   joints: [right_joint_gripper_l, right_joint_gripper_r]
 }
}
