controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
  - name: fake_right_arm_controller
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
  - name: fake_left_gripper_controller
    joints:
      - left_joint_gripper_r
  - name: fake_right_gripper_controller
    joints:
      - right_joint_gripper_l
      - right_joint_gripper_r