sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /vision/points/except_object
    max_range: 2.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    frame_subsample: 1
    # this last topic is just to debug, having it adds processing time
    # filtered_cloud_topic: filtered_cloud